sudo: required
services:
  - docker

before_install:
  - docker build -t izhonline/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true izhonline/react-test npm test -- --coverage

after_success:
  - docker build -t izhonline/multi-client ./client
  - docker build -t izhonline/multi-nginx ./nginx
  - docker build -t izhonline/multi-server ./server
  - docker build -t izhonline/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take the images and push them to the Docker Hub
  - docker push izhonline/multi-client
  - docker push izhonline/multi-nginx
  - docker push izhonline/multi-server
  - docker push izhonline/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-753216287855
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
